"""deleting the past event tabel

Revision ID: 057b8e5bf8cf
Revises: cd8c967454ec
Create Date: 2025-09-13 18:03:22.205553

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '057b8e5bf8cf'
down_revision = 'cd8c967454ec'
branch_labels = None
depends_on = None


def upgrade():
    # Be tolerant if legacy tables are already absent
    op.execute("DROP TABLE IF EXISTS event_sessions")
    op.execute("DROP TABLE IF EXISTS past_events")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_sessions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('session_type', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('image_path', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('display_order', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['past_events.id'], name=op.f('event_sessions_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('past_events',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('date', mysql.DATETIME(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('location', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('main_image', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('display_order', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
