"""Add membership fields to member table

Revision ID: 6fa758e44d64
Revises: 
Create Date: 2025-06-12 12:57:09.102419

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6fa758e44d64'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('membership_details')
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('membership_type', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('residence_phone', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('spouse_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('number_of_children', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('spouse_birth_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_column('spouse_birth_date')
        batch_op.drop_column('number_of_children')
        batch_op.drop_column('spouse_name')
        batch_op.drop_column('residence_phone')
        batch_op.drop_column('amount_paid')
        batch_op.drop_column('membership_type')

    op.create_table('membership_details',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('membership_type', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('amount_paid', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('residence_phone', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('spouse_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('number_of_children', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('spouse_birthdate', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
