"""Add the past event table

Revision ID: cd8c967454ec
Revises: 78be8f4f73dc
Create Date: 2025-09-13 17:43:45.039612

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cd8c967454ec'
down_revision = '78be8f4f73dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('session_type', sa.String(length=20), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['past_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('past_event_images')
    op.drop_table('past_event_sections')
    with op.batch_alter_table('past_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('main_image', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('display_order', sa.Integer(), nullable=True))
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.drop_column('is_published')
        batch_op.drop_column('venue')
        batch_op.drop_column('banner_image')
        batch_op.drop_column('chief_guest')
        batch_op.drop_column('event_summary')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('past_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_summary', mysql.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('chief_guest', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('banner_image', mysql.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('venue', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('is_published', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.alter_column('date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
        batch_op.drop_column('display_order')
        batch_op.drop_column('is_active')
        batch_op.drop_column('main_image')
        batch_op.drop_column('description')
        batch_op.drop_column('location')

    op.create_table('past_event_sections',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('past_event_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('section_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('section_icon', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('display_order', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['past_event_id'], ['past_events.id'], name='past_event_sections_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('past_event_images',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('section_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_path', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('image_caption', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('display_order', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['past_event_sections.id'], name=op.f('past_event_images_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('event_sessions')
    # ### end Alembic commands ###
